### ISSUE TITLE
Liquid error: uninitialized constant Jekyll::TweetTag::Net  

### ISSUE THREAD

**Issue by brunosan** [scottwb/jekyll-tweet-tag#1]
Trying to use your code, but it throws an error.

Any idea why this broke?

Thanks!

**Comment by scottwb** [comment]
What versions of Ruby and Octopress are you using? It might be that in the environment I was originally testing in, 'net/http' was already required, but perhaps it is not in your particular environment. You might try adding this line to the top of `tweet_tag.rb`:

```
require 'net/http'
```

**Comment by brunosan** [comment]
Thanks!
I´m not using Octopress, but adding 

```
require 'digest/md5'
require 'net/http'
```

fixed the problem.

**Comment by scottwb** [comment]
Cool. I guess I never tested this outside of Octopress. I'll take a look at reproducing this and perhaps adding those requires to master.

**Comment by Mierdin** [comment]
Same fix worked / was required for me. Using jekyll 2.5.3
